### ISSUE TITLE
what do you think about it ?

### ISSUE THREAD

**Issue by artemzi** [dudarev/photoplanet#1]
here is example(commit) - https://github.com/unSaint/photoplanet-1/commit/fe7a7e4b566fb9e4363562cdb52664648db34550

question is: why we use LoginRequiredMixin instead of login_required?

**Comment by artemzi** [comment]
i understand it`s only required login, and LoginRequiredMixin - do all validation... :)

**Comment by dudarev** [comment]
I'll explain it more in "Questions and Answers document in Google Docs". But to answer it briefly, using `LoginRequiredMixin` seems more natural with CBV. It makes code more concise and more readable. With FBV it is natural to use `@login_required` decorator for the same purpose.
