### ISSUE TITLE
Set up Ansible scripts to deploy on a given machine

### ISSUE THREAD

**Issue by dudarev** [dudarev/photoplanet#9]
Following instructions at

https://gist.github.com/dudarev/4348689#set-up-django-nginx-and-uwsgi

set up Ansible scripts to deploy photoplanet on VM.

Test with local [Vagrant](http://www.vagrantup.com/) instance.

**Comment by Ku-Al** [comment]
- [x] Fix error file permissions nginx + uwsgi
- [x] Ansible templates
- [x] Test Ansible templates in Vagrant
- [x] write documentation for deploy Django and Ansible config file

**Comment by dudarev** [comment]
For stand-alone server deployment I'm referring to this settings file:

https://github.com/dudarev/photoplanet/blob/master/photoplanet/photoplanet/settings/donetskogram.py

**Comment by Ku-Al** [comment]
Starting the application causes an error uwsgi:
In /home/photoplanet/photoplanet/logs/uwsgi.log
Traceback (most recent call last):
 self.method = environ['REQUEST_METHOD'].upper()
KeyError: u'REQUEST_METHOD'
[pid: 15270|app: 0|req: 3/4]() {14 vars in 359 bytes} [Wed Sep 10 17:23:22 2014]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)

**Comment by Ku-Al** [comment]
Fix KeyError
